### ISSUE TITLE
System Font Stack Review

### ISSUE THREAD

**Issue by bitstarr** [atomiks/30-seconds-of-css#10]
Hi,

I suggest to change the order of the first two fonts from ´´-apple-system, BlinkMacSystemFont,´´ to ´´BlinkMacSystemFont, -apple-system,´´.

Otherwise IE will use a serif font, which is the opposite of the intended behaviour.

**Comment by atomiks** [comment]
Which IE? GitHub itself puts `-apple-system` first

**Comment by Chalarangelo** [comment]
In general, `-apple-system` comes before `BlinkMacSystemFont` in most font stacks I have seen.

**Comment by mantlecurve** [comment]
In ubuntu, the font i set for UI is not working. Probably need to use `system-ui`

**Comment by atomiks** [comment]
@mantlecurve 

Does this work? 
```
-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol"
```

**Comment by mantlecurve** [comment]
This one works
`-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol"`

**Comment by atomiks** [comment]
@mantlecurve check this article about using `system-ui`: https://infinnie.github.io/blog/2017/systemui.html

**Comment by mantlecurve** [comment]
That makes sense. But in my case i wanted the system-ui font. I have seen spectre.css use it. That's why suggested.

**Comment by Chalarangelo** [comment]
In my opinion, `system-ui` should not be part of the font stack presented in the snippet. People might get in trouble using it and, if they actually need it, like @mantlecurve, they can always include it in their code. Snippets are supposed to be good starting points for common tasks, helping people get a project working. Everyone is encouraged to modify them to fit their specific needs and projects.

**Comment by Chalarangelo** [comment]
The current font stack works quite well on most systems and, having done some research, it's quite versatile, so we're gonna stick with it for now. However, it most certainly cannot acommodate everyone's needs. Snippets are a starting point for common tasks and we encourage developers to tweak them and alter them to suit their needs.
