### ISSUE TITLE
Clearfix caveats

### ISSUE THREAD

**Issue by SelenIT** [atomiks/30-seconds-of-css#11]
The "clearfix" snippet is marked as having no caveats. Hovewer, it's relying on the two assumptions and might fail if they are not true:

1. There are no non-floating children in the container (example where such a child apparently breaks clearfix: http://jsfiddle.net/o9rbryxp/16/);
2. There are no tall floats before the clearfixed container but in the same formatting context, e.g. floated columns (example of clearfix resulting in probably not the result that was expected, in comparison with new block formatting creation: https://codepen.io/SelenIT/pen/qrORXm/).

Shouldn't the users of the snipped be warned about these limitations?

**Comment by atomiks** [comment]
I believe so, feel free to make a PR addressing these 🕊
