### ISSUE TITLE
Twitter Credit/Visibility?

### ISSUE THREAD

**Issue by trainorpj** [atomiks/30-seconds-of-css#2]
Hey @atomiks, this is really fantastic.  So fantastic that I [tweeted about it](https://twitter.com/pj_trainor/status/967813110378713088).

I was looking for some way to tweet this out, but I just copy/pasted the link.  So I have two questions for you:

1. Do you have a twitter handle?  I'd love to give you credit (and so would others, I'm sure)
2. Have you considered adding twitter functionality?  Maybe just a button that prepares a tweet with the link to the site?... 
    * maybe even some capability to tweet out individual sections, if you're thinking about *really* expanding things 🚀

Once again, nice job.  I'm a big fan 🥇

**Comment by atomiks** [comment]
Thanks for tweeting it 😄! I don't have a twitter handle no, but I understand how popular twitter is in the dev community because I constantly see links to it so I'll definitely consider this.

**Comment by trainorpj** [comment]
Sounds good! The site is just fine without it, but let me know if you need any help in the future 🤝
