### ISSUE TITLE
Pretty text underline isn't so pretty

### ISSUE THREAD

**Issue by xori** [atomiks/30-seconds-of-css#22]
This might be a personal preference, but that underline doesn't look pretty to me.

![image](https://user-images.githubusercontent.com/1091220/36746119-806b1ff8-1bbf-11e8-9230-70a76722b04b.png)

Windows 10, Chrome 64.0.3282.167

**Comment by atomiks** [comment]
<img src="https://i.gyazo.com/7811352b0dfb7b4bd856320293c8d9e1.png">

It should be more like this. I'm guessing `em` might stuff up when a different font is used.

**Comment by Muhnad** [comment]
@atomiks @xori  we can use `text-decoration-skip-ink`  but this is not supported yet in all browsers.

[text-decoration-skip-ink](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip-ink)
[text-decoration-skip:](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-skip)

**Comment by atomiks** [comment]
This should be ok now since it uses a websafe font like Arial. But I'll consider different methods (not the native one) soon.
