### ISSUE TITLE
Edit Contributing template

### ISSUE THREAD

**Issue by Varunram** [atomiks/30-seconds-of-css#29]
Hey, nice project there. I see that the contributing template has some stuff missing. I'd be happy to put in a PR if you could tell what's needed (or remove the sections entirely).

**Comment by atomiks** [comment]
Thanks, which stuff? Feel free to make a PR with any changes

**Comment by Varunram** [comment]
This one: https://github.com/atomiks/30-seconds-of-css/blob/master/CONTRIBUTING.md

**Comment by atomiks** [comment]
Click `Raw` for everything. Or is that what you saw?

**Comment by Varunram** [comment]
Yeah, that's what I saw. Liens with `<!--` are automatically commented and I thought it'd be better to have something in the html and css sections or remove them entirely if nothing can be put there.

**Comment by Chalarangelo** [comment]
@Varunram the lines that contain `<!--` are comments that you can only see when editing the file, so that they do not make it into the final results. The idea is for that file to be edited to create new snippets.

**Comment by Varunram** [comment]
Ah, makes sense now, Thanks!
