### ISSUE TITLE
Super nice, but you could  credit authors :) 

### ISSUE THREAD

**Issue by LukyVj** [atomiks/30-seconds-of-css#33]
I like this project a lot, and it's similar to a project of mine. 
While scrolling on your page tho, I've noticed a few css thingy I've seen on codepen and elsewhere, and I thought it would be cool to credit the authors :) 

Like this one :)  https://codepen.io/electerious/pen/MQrRxX

**Comment by sinout** [comment]
@LukyVj Snippets provided in this project are built using native css/js features. They are not using any external libraries or authored projects. So I think no credits needed.

**Comment by LukyVj** [comment]
Hey! Thanks for your quick response :) 
I meant the concepts, and not the features used.
