### ISSUE TITLE
[FEATURE] On the spot experimentation feature

### ISSUE THREAD

**Issue by kriadmin** [atomiks/30-seconds-of-css#4]
Add an option to edit the `CSS` to experiment freely. `30-seconds-of-code` is basically all JS so we can easily copy paste in the browser console but in this project to experiment with some other values, we have to go to CodePen or something same. I would recommend making something of your own to change the CSS of the demo but you might even use some external service.

**Comment by Chalarangelo** [comment]
If I may add my two cents to this discussion, Codepen has an easy URL-based API where you can send your HTML/CSS/JS code along with dependencies and a name to create a new pen. Maybe you can use some advanced JS magic to generate links with all the necessary code for each snippet to make Codepens for people to test the code and play around with it.

**Comment by atomiks** [comment]
I thought of this while making it (particularly the triangle snippet), so yeah I'd say it's a good idea 😄

**Comment by kriadmin** [comment]
@atomiks  @Chalarangelo  Can't we just create a style-element for each snippet with the id as it's name and then change the innerHTML as what the user provides. We can make add content-editable on double-click. The idea of using codepen is good but won't it take time?
