### ISSUE TITLE
[BUG] Disable Select

### ISSUE THREAD

**Issue by CITguy** [atomiks/30-seconds-of-css#41]
FYI: `user-select: none;` isn't foolproof.  While it may prevent direct highlighting, it doesn't prevent selecting through the unselectable content. 

I'll let this gif do the talking.

![selecting-the-unselectable-10fps](https://user-images.githubusercontent.com/545605/36826779-5736afaa-1cd5-11e8-94cb-f3fa47d8370c.gif)

Chrome Version 64.0.3282.167

**Comment by atomiks** [comment]
I'm not sure anyone intends to use it to prevent someone copying content? It's mainly for buttons or icons that should be visual without being selectable.

**Comment by wasnlosdu** [comment]
Hey @CITguy , the W3 spec has some usefull information on this topic.
[They write](https://drafts.csswg.org/css-ui-4/#valdef-user-select-none):
> [...] This specification makes no normative requirement about the behavior of the clipboard. however, UAs are encouraged to keep the visual selection consistent with what would get copied to the clipboard when copying. Copying text that does not appear to be selected, or vice versa, is highly confusing to users. [...]

So I don't know if this is the right place to report it.
But thank you for the information 🐈

**Comment by Chalarangelo** [comment]
Could be added as a note that this is not a secure method to prevent copying. I don't think there's a lot of other options about this anyways.

**Comment by equinusocio** [comment]
...and if you can read it. You can copy (rewrite) it :)
