### ISSUE TITLE
MDN browser compatibility data

### ISSUE THREAD

**Issue by equinusocio** [atomiks/30-seconds-of-css#50]
Hi, MDN is making a tool to handle his browser compat data to show on the MDN site. Can this help for this project?

https://github.com/mdn/browser-compat-data

It is pretty simple:

```js
const bcd = require('mdn-browser-compat-data');
bcd.css.properties.background;
// returns a compat data object (see schema)
```

**Comment by atomiks** [comment]
`caniuse-db` seems to work fine for most features but we'll see

**Comment by Chalarangelo** [comment]
I suggest we close this for now, as `caniuse-db` is a mature tool that works quite well so far. MDN's information on browser support has been outdated in the past and it might take a while for their tool to mature and be ready to use. Plus, I see no reason to switch if we already have a working solution.

**Comment by equinusocio** [comment]
I was thinking more to use this with the can i use db. Not a switch. But ok 👍🏻🙂

**Comment by Chalarangelo** [comment]
@equinusocio Could you elaborate a bit about that idea?

**Comment by equinusocio** [comment]
Nothing to say :) I was just thinking that maybe you can use both data from caniuse and mdn (when caniuse does not cover it). But as you said, `caniuse-db` is a mature tool that works quite well so far.
