### ISSUE TITLE
[FEATURE] Translate Project

### ISSUE THREAD

**Issue by ribeiroevandro** [atomiks/30-seconds-of-css#52]
Fantastic this project, have thought to make the translation of it to other languages?

**Comment by atomiks** [comment]
In the future definitely, but not right now as there are more important things I need to do (people can translate the text using their browser at the moment).

**Comment by ribeiroevandro** [comment]
I understand, I will make a fork of the project and I will do the translations gradually, it will be a way to study and improve my level of English...

**Comment by fejes713** [comment]
Thanks for pointing that out @ribeiroevandro. Right now the project is in the pretty young state. There is no need to translate it for now. Later, as our user base grows and we get more contributors we can reopen this issue.
