### ISSUE TITLE
Lobotomized selector instead of ':not selector'

### ISSUE THREAD

**Issue by acidrums4** [atomiks/30-seconds-of-css#82]
Hello there,

I think for situations like described on ':not selector' (when you have, say, an unordered list rendered as a horizontal menu and you want borders between them, but not the left-border of the first element or the right-border of the last... you know what I mean) it's way more simple and elegant to use [the lobotomized owl selector](https://css-tricks.com/lobotomized-owls/).

So instead of doing

```
li:not(:last-child) {
  border-right: 2px solid #d2d5e4;
}
```

You just can do

```
li+li {
  border-left: 2px solid #d2d5e4;
}
```

And _voilà_, the same effect and saving a few bites on CSS. :)

**Comment by Chalarangelo** [comment]
The second code snippet will actually select everything except for the `:first-child` as it is applied to the last element in the selector. Unfortunately, CSS has no way to stylize a previous element in the hierarchy (meaning you cannot look ahead to check if there is an element of a specific type following an element that you want to stylize).

**Comment by acidrums4** [comment]
Well, I think this went lost into translation...

At least hope you did notice the first example with `border-right` against my example with `border-left` and the intention to do that.

**Comment by atomiks** [comment]
I think it can be added as a new snippet because it's interesting 😄
