### ISSUE TITLE
[ Height transition ] it's un useful by max-height （question）

### ISSUE THREAD

**Issue by maxxiaobao** [atomiks/30-seconds-of-css#92]
On the example https://codepen.io/anon/pen/jxaWQw, use JavaScript to control the `max-height`,
 I try to use css to finish like below
```
.el {
  transition: max-height 0.5s;
  overflow: hidden;
  max-height: 0;
}
.trigger:hover > .el {
  max-height: 100%;
}
```
 The result is: when you hover the trigger, the content will showing, but no transition.
This makes me confused, could you tell me the reason when you have time, thanks a lot!

**Comment by atomiks** [comment]
The `max-height` needs to be set the variable:

```css
.trigger:hover > .el {
  max-height: var(--max-height);
}
```

**Comment by maxxiaobao** [comment]
thanks
